#!/usr/bin/env bash
###############
## ES-Ubuntu ##
##           ##
## Runner    ##
## Configs   ##
###############

# Strict mode
set -euo pipefail
IFS=$'\n\t'

# Parse options
filter="${1:-}"

# Get script dir
base_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

# Bash init
run-parts --exit-on-error --regex="${filter}" "${base_dir}/init"
# Tools
run-parts --exit-on-error --regex="${filter}" "${base_dir}/tools"
