##########################################################################################################################
## ES-Ubuntu                                                                                                            ##
##                                                                                                                      ##
## Packages                                                                                                             ##
## Ansible collections requirements file                                                                                ##
## https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#install-multiple-collections-with-a-requirements-file ##
##########################################################################################################################
---
collections:
    - community.general
    - community.mysql
