#!/usr/bin/env bash
###############
## ES-Ubuntu ##
##           ##
## Config    ##
## gnupg     ##
###############

# Strict mode
set -euo pipefail
IFS=$'\n\t'

# Import library
source "${PATH_SOURCER}"

# Check if not run as root
check-not-root

echo -n "Copy gnupg config files..."
mkdir -p ~/.gnupg
cp "${ESUBUNTU_HOME}/custom/gpg/gpg-agent.conf" ~/.gnupg/
print-finish

exit 0
