#!/usr/bin/env bash
#################
## ES-Ubuntu   ##
##             ##
## Config      ##
## User groups ##
#################

# Strict mode
set -euo pipefail
IFS=$'\n\t'

# Check if not run as root
if [[ $(id -u) -eq 0 ]]; then
    echo "Don't run as root!"
    exit 1
fi

echo "Adding user to groups..."
sudo adduser "${USER}" users
sudo adduser "${USER}" www-data
echo -e "\e[32m\e[1mDone\e[0m"

exit 0
