#!/usr/bin/env bash
###############
## ES-Ubuntu ##
##           ##
## Config    ##
## Home dir  ##
###############

# Strict mode
set -euo pipefail
IFS=$'\n\t'

# Check if not run as root
if [[ $(id -u) -eq 0 ]]; then
    echo "Don't run as root!"
    exit 1
fi

# Remove default dirs
echo -n "Remove def dirs..."
rm -rf ~/Desktop ~/Documents ~/Downloads ~/Music
rm -rf ~/Pictures ~/Public ~/Templates ~/Videos
echo -e "\e[32m\e[1mDone\e[0m"

# Add new dirs
if [[ -d "${ESUBUNTU_HOME}/local" ]]; then # Local dir exists
    cd "${ESUBUNTU_HOME}/local"

    if [[ -f custom/user-dirs/home-dirs ]]; then # Local dirs file exists
        echo -n "Create home dirs..."
        while read -r line; do
            # eval line to let the shell expand tilde and env vars
            arg=$(eval echo "${line}")
            mkdir -p "${arg}"
        done < custom/user-dirs/home-dirs
        echo -e "\e[32m\e[1mDone\e[0m"
    fi
fi

# Permissions
echo -n "Setting permission on /home..."
sudo chown -R "${USER}:${USER}" ~
chmod -R go-rwx ~
echo -e "\e[32m\e[1mDone\e[0m"

exit 0
