#!/usr/bin/env bash
##################
## Zephyr       ##
##              ##
## Example      ##
## Local script ##
##################

# Strict mode
set -eufo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091
source "${PROJECT_ROOT}/bin/bootstrap.sh"
check-not-root

print-status Copy cron job...
sudo install --no-target-directory files/cron-script.sh /opt/cron-script
print-finish

print-status Configuring lftp...
sudo install --mode=0644 files/lftp.conf /etc/
print-finish

exit 0
