#!/usr/bin/env bash
##################
## Zephyr       ##
##              ##
## Example      ##
## Local script ##
##################

# Strict mode
set -eufo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091
source "${PROJECT_ROOT}/bin/bootstrap.sh"
check-not-root

print-status Copy cron job...
sudo cp --no-preserve=mode,ownership files/cron-script.sh /opt/cron-script
sudo chmod +x /opt/cron-script
print-finish

print-status Configuring lftp...
sudo cp --no-preserve=mode,ownership files/lftp.conf /etc/lftp.conf
print-finish

exit 0
