#!/usr/bin/env bash
##################
## Zephyr       ##
##              ##
## Example      ##
## Local script ##
##################

# Strict mode
set -eufo pipefail
IFS=$'\n\t'

echo Running local script...
pwd
echo Finished

exit 0
