name: CI
on:
  pull_request:
    branches:
      - main
    paths:
      - "bin/**"
jobs:
  code-style:
    name: Check code style (beautysh)
    runs-on: ubuntu-20.04
    steps:
      - name: Install beautysh
        run: sudo pip install beautysh

      - name: Self checkout
        uses: actions/checkout@v3

      - name: Check code-style
        run: find bin/ -type f -print0 | xargs -0 beautysh --force-function-style paronly --check
