name: CI
on:
  pull_request:
    branches:
      - main
    paths:
      - "bin/**"
jobs:
  # format:
  #   name: Check format
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - name: Install beautysh
  #       run: sudo pip install beautysh
  #
  #     - name: Self checkout
  #       uses: actions/checkout@v3
  #
  #     - name: Check code-style
  #       run: find bin/ -type f -print0 | xargs -0 beautysh --force-function-style paronly --check
  # linter:
  #   name: Linting
  #   runs-on: ubuntu-20.04
  #   needs: format
  #   steps:
  #     - name: Self checkout
  #       uses: actions/checkout@v3
  #
  #     - name: Run shellcheck
  #       uses: ludeeus/action-shellcheck@master
  #       env:
  #         SHELLCHECK_OPTS: --external-sources --enable add-default-case,avoid-nullary-conditions,check-extra-masked-returns,check-set-e-suppressed,deprecate-which,quote-safe-variables,require-double-brackets,require-variable-braces --shell bash
  #       with:
  #         severity: style
  check:
    name: Check for changed files
    runs-on: ubuntu-20.04
    # needs: linter
    outputs:
      apps: ${{ steps.modules.outputs.apps }}
      gnome: ${{ steps.modules.outputs.gnome }}
      packages: ${{ steps.modules.outputs.packages }}
      random: ${{ steps.modules.outputs.random }}
      services: ${{ steps.modules.outputs.services }}
      shell: ${{ steps.modules.outputs.shell }}
      system: ${{ steps.modules.outputs.system }}
      tools: ${{ steps.modules.outputs.tools }}
    steps:
      - name: Self checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        run: git diff --numstat origin/main... | awk '{print $3'} > ~/changed.files

      - name: Check changed modules
        id: modules
        run: |
          if grep -qs customize/apps ~/changed.files; then
            echo "::set-output name=apps::yes"
          fi
          if grep -qs customize/gnome ~/changed.files; then
            echo "::set-output name=gnome::yes"
          fi
          if grep -qs customize/packages ~/changed.files; then
            echo "::set-output name=packages::yes"
          fi
          if grep -qs customize/random ~/changed.files; then
            echo "::set-output name=random::yes"
          fi
          if grep -qs customize/services ~/changed.files; then
            echo "::set-output name=services::yes"
          fi
          if grep -qs customize/shell ~/changed.files; then
            echo "::set-output name=shell::yes"
          fi
          if grep -qs customize/system ~/changed.files; then
            echo "::set-output name=system::yes"
          fi
          if grep -qs customize/tools ~/changed.files; then
            echo "::set-output name=tools::yes"
          fi
        shell: bash
  tests-apps:
    name: Integration tests (customize/apps)
    runs-on: ubuntu-20.04
    needs: check
    if: needs.check.outputs.apps == 'yes'
    steps:
      - name: Self checkout
        uses: actions/checkout@v3

      - name: Link profiles
        run: ln -s example profiles

      - name: Install dependencies
        run: |
          sudo add-apt-repository --yes ppa:mikhailnov/pulseeffects
          sudo apt-get install --yes --no-install-recommends pulseeffects virtualbox

      - name: Execute scripts (1st pass)
        run: |
          ./bin/esubuntuctl customize default atom
          ./bin/esubuntuctl customize default jmeter
          ./bin/esubuntuctl customize default pulse-effects
          ./bin/esubuntuctl customize default virtualbox
        shell: bash

      - name: Execute scripts (2nd pass)
        run: |
          ./bin/esubuntuctl customize default atom
          ./bin/esubuntuctl customize default jmeter
          ./bin/esubuntuctl customize default pulse-effects
          ./bin/esubuntuctl customize default virtualbox
        shell: bash
